### ISSUE TITLE
Clock Widget Does Not Update The Date

### ISSUE THREAD

**Issue by SevenFactors** [BlackyHawky/Clock#212]
**Describe the bug**

Clock widget does not update the date. This has been happening since v2.13. It is still present in v2.14
The widget I use is the classic one which is white by default and the colors, background, etc can be customized.

**To Reproduce**

Just setup the app, place the widget on desktop launcher and wait till the next day to see that the widget is displaying the previous date.

The only way to force the widget to update the date is by holding the widget till it triggers the edit. Might required to resize it.

**Expected behavior**

To work as expected by keeping time and date accurately. 

**Screenshots**

**App version**

Current App version" 2.14

**Device (please complete the following information):**
 - Model:  Pixel 5a
 - OS: GrapheneOS version: 2025021000

**Additional context**

**Comment by SevenFactors** [comment]
Looking at the releases, I see on the logs that this has been fixed. 

I was going to create another issue about my app resetting itself as if the app's storage  had been deleted. Lost all my alarms, timers, etc.

I will wait till v2.15 reaches fdroid and give it another run before making t his issue in case this has been fixed there.

**Comment by BlackyHawky** [comment]
@SevenFactors 
> I was going to create another issue about my app resetting itself as if the app's storage had been deleted. Lost all my alarms, timers, etc.

This is very strange as it has never happened on my devices 🤔
Especially since I haven't made any changes that could lead to this kind of behavior.

> I will wait till v2.15 reaches fdroid and give it another run before making t his issue in case this has been fixed there.

It takes so long to get updates with F-Droid...
In any case, don't hesitate to keep me informed 😉

**Comment by edent** [comment]
This bug is still present. My home timezone is London (GMT) and my current timezone is Auckland (GMT+13).

The world clock widget shows the wrong day for the current timezone.

<img width="644" height="644" alt="both days are Saturday." src="https://github.com/user-attachments/assets/f7d4174e-b4f5-408b-8e8e-2b677e1498e6" />

When I resize the widget, the date corrects.

<img width="638" height="638" alt="local day is Sunday home day is Saturday." src="https://github.com/user-attachments/assets/4456258b-6bb6-4ba5-bcae-564d594b0d03" />

Version 2.26 from F-Droid.

com.best.deskclock
versionCode 2029

targetSdk 35
minSdk 23

Installed: 26 Dec 2025; 06:35

Running on Pixel 8 Pro, Android 16 (GrapheneOS 2025121701)

**Comment by BlackyHawky** [comment]
@edent 
Hi,

It's not (entirely) the app's fault, but rather that of Android 16. See the discussion in #200.
